### ISSUE TITLE
安卓端没找到翻页功能选项。

### ISSUE THREAD

**Issue by yuxiaobian** [dtysky/Awaken#1]
手机型号：Redmi Note 11T Pro 系统：MIUI 13.014
电纸书型号：MatePad Paper 
问题描述：安卓的这两个设备在运行软件时，点击，滑动都不翻页。

**Comment by dtysky** [comment]
阅读界面点击左右两侧**空白区域**理论可以翻页，区域是有点窄看是不是点到文字了，滑动暂时没空懒得做，凑合用吧。
