### ISSUE TITLE
添加书籍的时候提示failed to fetch

### ISSUE THREAD

**Issue by primejava** [dtysky/Awaken#2]
尝试了几本书都是导入失败

**Comment by dtysky** [comment]
信息太少，无法判断。

**Comment by jinnnyang** [comment]
我也出现了相同的问题，
系统：Windows 10 21H2
WebDAV：坚果云

如下动图所示
![Fail to fech](https://user-images.githubusercontent.com/78803748/211130319-75e4786c-b1c0-4fa3-8f22-80c5f2116d5e.gif)

**Comment by dtysky** [comment]
将在1.0.1解决，明天更新资源包。
