### ISSUE TITLE
平板界面电子书显示不全

### ISSUE THREAD

**Issue by Asteroidmple** [dtysky/Awaken#6]
横屏情况下书架页无法上下滑动，只能显示最上面的几本书，下面的没法浏览
竖屏状态下打开的书籍转到横屏会自动关闭
平板型号HUAWEI Matepad 11 系统Harmony OS 3.0

**Comment by dtysky** [comment]
问题1将在1.0.1解决，明天更新资源包。
问题2不影响使用，就这样吧。
